import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  Pressable,
  Alert,
  Share,
  Platform,
} from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { COLORS, FONTS, SIZES } from '../../constants/theme';
import { useSettingsStore } from '../../src/stores/settingsStore';
import { useVotesStore } from '../../src/stores/votes';
import { useKinks } from '../../lib/data';

export default function ExportMatches() {
  const insets = useSafeAreaInsets();
  const unlocked = useSettingsStore((state) => state.unlocked);
  const language = useSettingsStore((state) => state.language);
  const { kinks } = useKinks(language === 'es' ? 'es' : 'en');
  const votes = useVotesStore((state) => state.votes);
  
  const [exporting, setExporting] = useState(false);

  // Get mutual yes matches
  const matches = React.useMemo(() => {
    const yesVotes = Object.entries(votes).filter(([, vote]) => vote === 'yes');
    return yesVotes.map(([id]) => kinks.find(k => k.id === id)).filter(Boolean);
  }, [votes, kinks]);

  const generateTextExport = () => {
    const header = `💕 SpiceSync Matches - ${new Date().toLocaleDateString()}\n\n`;
    const items = matches.map((match, index) => 
      `${index + 1}. ${match?.title}\n   ${match?.description}\n   Category: ${match?.category}\n   Intensity: ${match?.intensityScale}/5\n`
    ).join('\n');
    
    return header + items + `\n\nGenerated by SpiceSync`;
  };

  const generateCSVExport = () => {
    const header = 'Title,Description,Category,Intensity,Tags\n';
    const rows = matches.map(match => 
      `"${match?.title}","${match?.description}","${match?.category}",${match?.intensityScale},"${match?.tags?.join(', ')}"`
    ).join('\n');
    
    return header + rows;
  };

  const handleExport = async (format: 'text' | 'csv') => {
    if (!unlocked) {
      Alert.alert(
        'Premium Feature',
        'Exporting matches requires a premium subscription.',
        [
          { text: 'Cancel', style: 'cancel' },
          { text: 'Upgrade', onPress: () => {} },
        ]
      );
      return;
    }

    if (matches.length === 0) {
      Alert.alert('No Matches', 'You don\'t have any matches to export yet!');
      return;
    }

    setExporting(true);

    const content = format === 'text' ? generateTextExport() : generateCSVExport();
    const filename = `spicesync-matches-${new Date().toISOString().split('T')[0]}.${format}`;

    try {
      // Share the content
      await Share.share({
        message: content,
        title: `SpiceSync Matches (${matches.length})`,
      });
    } catch (error) {
      Alert.alert('Error', 'Failed to export matches');
    }

    setExporting(false);
  };

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.content}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>📤 Export Matches</Text>
          <Text style={styles.subtitle}>
            {unlocked 
              ? `${matches.length} matches ready to export`
              : 'Premium feature - unlock to export'
            }
          </Text>
        </View>

        {/* Export Options */}
        <View style={styles.optionsContainer}>
          {/* Text Export */}
          <Pressable 
            style={[
              styles.exportCard,
              !unlocked && styles.exportCardLocked,
            ]}
            onPress={() => handleExport('text')}
          >
            <Text style={styles.exportEmoji}>📝</Text>
            <View style={styles.exportInfo}>
              <Text style={styles.exportTitle}>Plain Text</Text>
              <Text style={styles.exportDescription}>
                Easy to read, perfect for sharing
              </Text>
            </View>
            {!unlocked && <Text style={styles.lockIcon}>🔒</Text>}
          </Pressable>

          {/* CSV Export */}
          <Pressable 
            style={[
              styles.exportCard,
              !unlocked && styles.exportCardLocked,
            ]}
            onPress={() => handleExport('csv')}
          >
            <Text style={styles.exportEmoji}>📊</Text>
            <View style={styles.exportInfo}>
              <Text style={styles.exportTitle}>CSV Spreadsheet</Text>
              <Text style={styles.exportDescription}>
                Import into Excel or Google Sheets
              </Text>
            </View>
            {!unlocked && <Text style={styles.lockIcon}>🔒</Text>}
          </Pressable>
        </View>

        {/* Preview */}
        {matches.length > 0 && (
          <View style={styles.previewCard}>
            <Text style={styles.previewTitle}>Preview</Text>
            <Text style={styles.previewText} numberOfLines={5}>
              {generateTextExport()}
            </Text>
          </View>
        )}
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  content: {
    flex: 1,
    padding: SIZES.padding * 2,
  },
  header: {
    marginBottom: SIZES.padding * 3,
  },
  title: {
    fontFamily: FONTS.bold,
    fontSize: SIZES.h1,
    color: COLORS.text,
    marginBottom: 4,
  },
  subtitle: {
    fontFamily: FONTS.regular,
    fontSize: SIZES.body,
    color: COLORS.textSecondary,
  },
  optionsContainer: {
    gap: SIZES.padding,
    marginBottom: SIZES.padding * 2,
  },
  exportCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.card,
    padding: SIZES.padding * 1.5,
    borderRadius: SIZES.radius,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  exportCardLocked: {
    opacity: 0.6,
  },
  exportEmoji: {
    fontSize: 32,
    marginRight: SIZES.padding,
  },
  exportInfo: {
    flex: 1,
  },
  exportTitle: {
    fontFamily: FONTS.bold,
    fontSize: SIZES.h4,
    color: COLORS.text,
    marginBottom: 4,
  },
  exportDescription: {
    fontFamily: FONTS.regular,
    fontSize: SIZES.small,
    color: COLORS.textSecondary,
  },
  lockIcon: {
    fontSize: 20,
  },
  previewCard: {
    backgroundColor: COLORS.card,
    padding: SIZES.padding,
    borderRadius: SIZES.radius,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  previewTitle: {
    fontFamily: FONTS.bold,
    fontSize: SIZES.body,
    color: COLORS.text,
    marginBottom: SIZES.padding,
  },
  previewText: {
    fontFamily: FONTS.regular,
    fontSize: SIZES.small,
    color: COLORS.textSecondary,
    lineHeight: 20,
  },
});
