// Couple Dice: three dice faces (mood, action, moment) combine into a
// natural-language, consent-forward prompt. Every mood×action pair has an
// explicit EN/ES template with a `{{moment}}` slot, so no combination can be
// grammatically broken — there is no runtime string concatenation of parts
// that were never checked together.
export type DiceMood = 'playful' | 'connected' | 'romantic' | 'adventurous';
export type DiceAction = 'talk' | 'compliment' | 'choose' | 'explore' | 'plan';
export type DiceMoment =
  | 'right_now'
  | 'this_evening'
  | 'this_week'
  | 'next_date_night';
export type DiceLanguage = 'en' | 'es';

export const DICE_MOODS: DiceMood[] = [
  'playful',
  'connected',
  'romantic',
  'adventurous',
];
export const DICE_ACTIONS: DiceAction[] = [
  'talk',
  'compliment',
  'choose',
  'explore',
  'plan',
];
export const DICE_MOMENTS: DiceMoment[] = [
  'right_now',
  'this_evening',
  'this_week',
  'next_date_night',
];

const MOMENT_TEXT: Record<DiceLanguage, Record<DiceMoment, string>> = {
  en: {
    right_now: 'right now',
    this_evening: 'this evening',
    this_week: 'this week',
    next_date_night: 'on your next date night',
  },
  es: {
    right_now: 'ahora mismo',
    this_evening: 'esta noche',
    this_week: 'esta semana',
    next_date_night: 'en su próxima noche de cita',
  },
};

type Template = (moment: string) => string;

// Keyed by `${mood}:${action}` so every combination is explicit and
// reviewable — nothing is generated by concatenating unchecked fragments.
const TEMPLATES: Record<DiceLanguage, Record<string, Template>> = {
  en: {
    'playful:talk': (m) =>
      `Talk about the silliest thing you find endearing about each other, ${m}.`,
    'playful:compliment': (m) =>
      `Give each other a playful compliment ${m} — bonus points for a nickname.`,
    'playful:choose': (m) =>
      `Choose one playful thing to do together ${m} — both of you get a say.`,
    'playful:explore': (m) =>
      `Explore a new playful activity idea together ${m}, just to see what you think.`,
    'playful:plan': (m) =>
      `Plan one lighthearted, low-stakes thing to try together ${m}.`,
    'connected:talk': (m) =>
      `Talk about a moment you felt closest to each other, ${m}.`,
    'connected:compliment': (m) =>
      `Tell each other one thing you appreciate about how you connect, ${m}.`,
    'connected:choose': (m) =>
      `Choose one small way to feel more connected ${m} — both of you get a say.`,
    'connected:explore': (m) =>
      `Explore what "feeling connected" means to each of you ${m}.`,
    'connected:plan': (m) => `Plan a little check-in with each other ${m}.`,
    'romantic:talk': (m) =>
      `Talk about what romance means to each of you, ${m}.`,
    'romantic:compliment': (m) =>
      `Share one romantic compliment with each other ${m}.`,
    'romantic:choose': (m) =>
      `Choose one small way to make ${m} feel more romantic — both of you get a say.`,
    'romantic:explore': (m) =>
      `Explore one romantic idea you'd both be open to trying ${m}.`,
    'romantic:plan': (m) => `Plan a small romantic gesture for ${m}.`,
    'adventurous:talk': (m) =>
      `Talk about something new you'd both be curious to try, ${m}.`,
    'adventurous:compliment': (m) =>
      `Compliment your partner's most adventurous quality ${m}.`,
    'adventurous:choose': (m) =>
      `Choose one adventurous thing to try ${m} — both of you get a say.`,
    'adventurous:explore': (m) =>
      `Explore an adventurous idea neither of you has tried, ${m}.`,
    'adventurous:plan': (m) =>
      `Plan one adventurous outing or activity for ${m}.`,
  },
  es: {
    'playful:talk': (m) =>
      `Hablen de lo más tierno y tonto que les gusta del otro, ${m}.`,
    'playful:compliment': (m) =>
      `Hagan un cumplido juguetón el uno al otro ${m} — puntos extra por un apodo.`,
    'playful:choose': (m) =>
      `Elijan algo juguetón para hacer juntos ${m} — ambos opinan.`,
    'playful:explore': (m) =>
      `Exploren juntos una nueva idea juguetona ${m}, solo para ver qué piensan.`,
    'playful:plan': (m) =>
      `Planeen algo ligero y sin presión para intentar juntos ${m}.`,
    'connected:talk': (m) =>
      `Hablen de un momento en que se sintieron más cerca, ${m}.`,
    'connected:compliment': (m) =>
      `Cuéntense algo que aprecian de cómo conectan, ${m}.`,
    'connected:choose': (m) =>
      `Elijan una pequeña forma de sentirse más conectados ${m} — ambos opinan.`,
    'connected:explore': (m) =>
      `Exploren qué significa "sentirse conectados" para cada uno, ${m}.`,
    'connected:plan': (m) =>
      `Planeen un pequeño momento para ver cómo están ${m}.`,
    'romantic:talk': (m) =>
      `Hablen de qué significa el romance para cada uno, ${m}.`,
    'romantic:compliment': (m) => `Compártanse un cumplido romántico ${m}.`,
    'romantic:choose': (m) =>
      `Elijan una pequeña forma de hacer que ${m} se sienta más romántico — ambos opinan.`,
    'romantic:explore': (m) =>
      `Exploren una idea romántica que ambos estarían dispuestos a intentar ${m}.`,
    'romantic:plan': (m) => `Planeen un pequeño gesto romántico para ${m}.`,
    'adventurous:talk': (m) =>
      `Hablen de algo nuevo que a ambos les daría curiosidad probar, ${m}.`,
    'adventurous:compliment': (m) =>
      `Hagan un cumplido sobre la cualidad más aventurera de su pareja ${m}.`,
    'adventurous:choose': (m) =>
      `Elijan algo aventurero con lo que ambos estén realmente de acuerdo ${m}.`,
    'adventurous:explore': (m) =>
      `Exploren una idea aventurera que ninguno haya probado, ${m}.`,
    'adventurous:plan': (m) =>
      `Planeen una salida o actividad aventurera para ${m}.`,
  },
};

export function buildDicePrompt(
  mood: DiceMood,
  action: DiceAction,
  moment: DiceMoment,
  language: DiceLanguage = 'en'
): string {
  const templates = TEMPLATES[language] ?? TEMPLATES.en;
  const momentText = (MOMENT_TEXT[language] ?? MOMENT_TEXT.en)[moment];
  const key = `${mood}:${action}`;
  const template = templates[key];
  if (!template) {
    throw new Error(`Missing Couple Dice template for combination: ${key}`);
  }
  return template(momentText);
}
